# Generated by Django 4.2.16 on 2026-09-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='current_level',
            field=models.CharField(choices=[('MENTOR', 'Mentor Level'), ('HOD', 'HOD Level'), ('PRINCIPAL', 'Principal Level')], default='MENTOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED_HOD', 'Escalated to HOD'), ('ESCALATED_PRINCIPAL', 'Escalated to Principal'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('REOPENED', 'Reopened')], default='SUBMITTED', max_length=25),
        ),
        migrations.AlterField(
            model_name='complaintstatushistory',
            name='new_status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='complaintstatushistory',
            name='old_status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'Student / User'), ('MENTOR', 'Mentor / Faculty'), ('HOD', 'Head of Department (HOD)'), ('PRINCIPAL', 'Principal'), ('ADMIN', 'System Administrator')], default='USER', max_length=20),
        ),
    ]
