# Generated by Django 4.2.16 on 2026-09-17 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0002_complaint_current_level_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='current_level',
            field=models.CharField(choices=[('MENTOR', 'Class Mentor Level'), ('HOD', 'HOD Level')], default='MENTOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED_HOD', 'Escalated to HOD'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('REOPENED', 'Reopened')], default='SUBMITTED', max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('CLASS_MENTOR', 'Class Mentor'), ('HOD', 'Head of Department (HOD)'), ('ADMIN', 'System Administrator')], default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Class',
                'verbose_name_plural': 'Academic Classes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='complaints.academicclass'),
        ),
    ]
