# Generated by Django 4.2.16 on 2026-09-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_current_level_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='current_level',
            field=models.CharField(choices=[('MENTOR', 'Class Mentor Level'), ('HOD', 'HOD Level'), ('PRINCIPAL', 'Principal Level')], default='MENTOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED_HOD', 'Escalated to HOD'), ('ESCALATED_PRINCIPAL', 'Escalated to Principal'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('REOPENED', 'Reopened')], default='SUBMITTED', max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('CLASS_MENTOR', 'Class Mentor'), ('HOD', 'Head of Department (HOD)'), ('PRINCIPAL', 'Principal'), ('ADMIN', 'System Administrator')], default='STUDENT', max_length=20),
        ),
    ]
