# Generated by Django 4.2.16 on 2026-09-17 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0005_alter_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintresponse',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
